# Generated by Django 5.1.7 on 2025-03-28 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportealumno',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='reportealumno',
            name='observacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.observacion'),
        ),
    ]
