# Generated by Django 5.1.7 on 2025-03-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_remove_reportealumno_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
