# Generated by Django 5.1.7 on 2025-03-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_estudiante_dni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportealumno',
            old_name='observacion',
            new_name='observaciones',
        ),
    ]
