# Generated by Django 5.1.7 on 2025-03-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_rename_observacion_reportealumno_observaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportealumno',
            old_name='observaciones',
            new_name='observacion',
        ),
    ]
